### ISSUE TITLE
Use Plone LESS variables when possible

### ISSUE THREAD

**Issue by davilima6** [collective/plonetheme.clean_blog#4]
For instance, instead of hard-coding margins for toolbar we'd be better off using `plone-left-toolbar` and `plone-left-toolbar-expanded` LESS variables:
- https://github.com/plone/plonetheme.barceloneta/blob/master/plonetheme/barceloneta/theme/less/variables.plone.less#L121-L122

Btw, in the same fashion I prefer to use Plone variables for media queries. Basically:

```
// Not mobile: Above 768px
@media (min-width: @plone-screen-sm-min) {
}

// Mobile: Below 767px
@media (max-width: @plone-screen-xs-max) {
}
```

**Comment by vikas-parashar** [comment]
Yeah, In the current theme 'spot' I'm using Plone variables, I'll update this theme also.
