### ISSUE TITLE
Resources not being loaded

### ISSUE THREAD

**Issue by davilima6** [collective/plonetheme.clean_blog#5]
Here's a screenshot just after enabling the theme in Plone 5.0.5:

![clearblog-broken-resources](https://cloud.githubusercontent.com/assets/422130/18545013/a75d1278-7b0d-11e6-8e69-4a9d0173431a.jpg)

It works after I go to `@@resourceregistry-controlpanel` and hit the `Build` button for `clean-blog-bundle`.

Btw, is there a release of this package in PyPI? I just found the one with similar name: https://pypi.python.org/pypi/plonetheme.clean-blog Also it'd be nice to move all themes repos to collective.

**Comment by vikas-parashar** [comment]
Unfortunately, There are lot of `Clean Blog` themes for Plone so I had to change the name. You can checkout the theme here https://pypi.python.org/pypi/plonetheme.cleanblog
It should work fine now.
